### ISSUE TITLE
User Authentication Issue - Login

### ISSUE THREAD

**Issue by andrewjohnson1053** [andrewjohnson1053/trekkin#21]
The userdata is not saved in the app and hence needs to log in every time we launch the app.
@YashwardhanChavan look into it. 
origin - pull request [#18]
for reference please visit [Firebase AuthUI Docs](https://firebase.google.com/docs/auth/android/password-auth?authuser=0)

**Comment by YashwardhanChavan** [comment]
Took care of it.
